# Generated by Django 6.0.6 on 2026-08-04 08:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_case_status_severity_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('Related', 'Related'), ('Duplicate of', 'Duplicate of'), ('Parent of', 'Parent of')], max_length=20)),
                ('note', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('pair_key', models.CharField(editable=False, max_length=73, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_relationships', to=settings.AUTH_USER_MODEL)),
                ('source_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='cases.case')),
                ('target_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='cases.case')),
            ],
            options={
                'db_table': 'case_relationships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_case', 'relationship_type'], name='case_rel_source_type_idx'), models.Index(fields=['target_case', 'relationship_type'], name='case_rel_target_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_case', models.F('target_case')), _negated=True), name='case_rel_no_self'), models.UniqueConstraint(condition=models.Q(('relationship_type', 'Parent of')), fields=('target_case',), name='case_rel_one_parent'), models.UniqueConstraint(condition=models.Q(('relationship_type', 'Duplicate of')), fields=('source_case',), name='case_rel_one_duplicate_target')],
            },
        ),
    ]
