from django.urls import path

from .views import (
    AgentVersionView,
    AlertDetailView,
    AlertListView,
    ArtifactDetailView,
    ArtifactListView,
    CaseAIAnalysisView,
    CaseDetailView,
    CaseListView,
    CaseRelationshipListView,
    CaseRelationshipSuggestionView,
    CommentListCreateView,
    EnrichmentCreateView,
    FileDetailView,
    FileReadTextView,
    FileUploadView,
    KnowledgeDetailView,
    KnowledgeListView,
    CMDBLookupView,
    DevStreamHeadView,
    DevStreamReadView,
    PlaybookDetailView,
    PlaybookListView,
    PlaybookRunView,
    PlaybookTemplateListView,
    SIEMAdaptiveQueryView,
    SIEMDiscoverFieldsView,
    SIEMESQLQueryView,
    SIEMKeywordSearchView,
    SIEMSchemaView,
    SIEMSPLQueryView,
    ThreatIntelQueryView,
)

urlpatterns = [
    path("version/", AgentVersionView.as_view(), name="agent-api-version"),
    path("cases/", CaseListView.as_view(), name="agent-api-case-list"),
    path("cases/<str:case_id>/", CaseDetailView.as_view(), name="agent-api-case-detail"),
    path("cases/<str:case_id>/ai-analysis/", CaseAIAnalysisView.as_view(), name="agent-api-case-ai-analysis"),
    path("cases/<str:case_id>/relationships/", CaseRelationshipListView.as_view(), name="agent-api-case-relationships"),
    path("cases/<str:case_id>/relationship-suggestions/", CaseRelationshipSuggestionView.as_view(), name="agent-api-case-relationship-suggestions"),
    path("alerts/", AlertListView.as_view(), name="agent-api-alert-list"),
    path("alerts/<str:alert_id>/", AlertDetailView.as_view(), name="agent-api-alert-detail"),
    path("artifacts/", ArtifactListView.as_view(), name="agent-api-artifact-list"),
    path("artifacts/<str:artifact_id>/", ArtifactDetailView.as_view(), name="agent-api-artifact-detail"),
    path("knowledge/", KnowledgeListView.as_view(), name="agent-api-knowledge-list"),
    path("knowledge/<str:knowledge_id>/", KnowledgeDetailView.as_view(), name="agent-api-knowledge-detail"),
    path("comments/", CommentListCreateView.as_view(), name="agent-api-comment-list-create"),
    path("files/", FileUploadView.as_view(), name="agent-api-file-upload"),
    path("files/<uuid:file_key>/", FileDetailView.as_view(), name="agent-api-file-detail"),
    path("files/<uuid:file_key>/read-text/", FileReadTextView.as_view(), name="agent-api-file-read-text"),
    path("enrichments/", EnrichmentCreateView.as_view(), name="agent-api-enrichment-create"),
    path("playbooks/templates/", PlaybookTemplateListView.as_view(), name="agent-api-playbook-template-list"),
    path("playbooks/", PlaybookListView.as_view(), name="agent-api-playbook-list"),
    path("playbooks/run/", PlaybookRunView.as_view(), name="agent-api-playbook-run"),
    path("playbooks/<str:playbook_id>/", PlaybookDetailView.as_view(), name="agent-api-playbook-detail"),
    path("siem/schema/", SIEMSchemaView.as_view(), name="agent-api-siem-schema"),
    path("siem/search/keyword/", SIEMKeywordSearchView.as_view(), name="agent-api-siem-keyword-search"),
    path("siem/query/adaptive/", SIEMAdaptiveQueryView.as_view(), name="agent-api-siem-adaptive-query"),
    path("siem/query/spl/", SIEMSPLQueryView.as_view(), name="agent-api-siem-spl-query"),
    path("siem/query/esql/", SIEMESQLQueryView.as_view(), name="agent-api-siem-esql-query"),
    path("siem/fields/discover/", SIEMDiscoverFieldsView.as_view(), name="agent-api-siem-discover-fields"),
    path("threat-intel/query/", ThreatIntelQueryView.as_view(), name="agent-api-threat-intel-query"),
    path("cmdb/lookup/", CMDBLookupView.as_view(), name="agent-api-cmdb-lookup"),
    path("dev/streams/head/", DevStreamHeadView.as_view(), name="agent-api-dev-stream-head"),
    path("dev/streams/message/", DevStreamReadView.as_view(), name="agent-api-dev-stream-read"),
]
