# Generated by Django 6.0.7 on 2026-08-05 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0002_playbook_playbook_created_job_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Execution finish time (执行结束时间)', null=True),
        ),
        migrations.AddField(
            model_name='playbook',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Execution start time (执行开始时间)', null=True),
        ),
        migrations.CreateModel(
            name='PlaybookRunMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playbook_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_messages', to='playbooks.playbook')),
            ],
            options={
                'db_table': 'playbook_run_messages',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['playbook_run', 'sequence'], name='playbook_msg_run_seq_idx')],
                'constraints': [models.UniqueConstraint(fields=('playbook_run', 'sequence'), name='playbook_msg_run_seq_uniq')],
            },
        ),
    ]
